// Historical performance data extracted from ~/My_KB/vimal_analysis_results.csv
// ticker → { pnl (%), reMentions, target, names }
// 80% win rate | 76% XIRR vs 12.5% Nifty50 (analysis date: Apr 2026)
export const VIMAL_HISTORY = {
  "BAJAJHIND.NS": { pnl: 153.5, reMentions: 3, target: 45, names: "bajaj hind" },
  "CANBK.NS": { pnl: 147.4, reMentions: 24, target: 350, names: "can, canara" },
  "ASHAPURMIN.NS": { pnl: 146.1, reMentions: 0, target: null, names: "ashapura" },
  "OMINFRAL.NS": { pnl: 128.0, reMentions: 4, target: 225, names: "om infra" },
  "JBMA.NS": { pnl: 125.1, reMentions: 0, target: null, names: "jbm" },
  "NCC.NS": { pnl: 119.1, reMentions: 5, target: 84, names: "ncc" },
  "TARC.NS": { pnl: 117.7, reMentions: 11, target: 75, names: "tarc" },
  "TEXRAIL.NS": { pnl: 112.7, reMentions: 10, target: 75, names: "texmeco" },
  "RPOWER.NS": { pnl: 112.1, reMentions: 3, target: null, names: "r power" },
  "SUNFLAG.NS": { pnl: 108.6, reMentions: 0, target: null, names: "sunflag" },
  "GODREJIND.NS": { pnl: 107.6, reMentions: 2, target: 2000, names: "godrej ind" },
  "HCC.NS": { pnl: 107.1, reMentions: 6, target: 100, names: "hcc" },
  "IRB.NS": { pnl: 106.7, reMentions: 3, target: null, names: "irb" },
  "NBCC.NS": { pnl: 105.2, reMentions: 0, target: 210, names: "nbcc" },
  "OLECTRA.NS": { pnl: 104.6, reMentions: 0, target: null, names: "olectra" },
  "ANANTRAJ.NS": { pnl: 102.6, reMentions: 6, target: 200, names: "anantraj" },
  "JPPOWER.NS": { pnl: 99.2, reMentions: 2, target: null, names: "jp power" },
  "VENUSREM.NS": { pnl: 99.1, reMentions: 1, target: 450, names: "venus remedies" },
  "KARURVYSYA.NS": { pnl: 94.9, reMentions: 0, target: 110, names: "karur vysya" },
  "DBL.NS": { pnl: 92.4, reMentions: 3, target: 2022, names: "dilip" },
  "SANDUMA.NS": { pnl: 91.9, reMentions: 3, target: 2500, names: "sandur" },
  "ISGEC.NS": { pnl: 90.2, reMentions: 1, target: null, names: "isgec" },
  "BFINVEST.NS": { pnl: 89.1, reMentions: 1, target: 1500, names: "bf investment" },
  "TIMETECHNO.NS": { pnl: 87.6, reMentions: 0, target: null, names: "timetechno" },
  "FEDERALBNK.NS": { pnl: 87.2, reMentions: 3, target: 175, names: "federal" },
  "HERITGFOOD.NS": { pnl: 81.4, reMentions: 0, target: null, names: "heritage food" },
  "KALYANKJIL.NS": { pnl: 80.5, reMentions: 3, target: 111, names: "kalyan" },
  "HUDCO.NS": { pnl: 80.1, reMentions: 0, target: 5000, names: "hudco" },
  "SEPC.NS": { pnl: 75.8, reMentions: 3, target: 44, names: "sepc" },
  "RBLBANK.NS": { pnl: 74.3, reMentions: 8, target: 200, names: "rbl" },
  "BLISSGVS.NS": { pnl: 74.2, reMentions: 7, target: 250, names: "bliss gvs" },
  "EMKAY.NS": { pnl: 70.8, reMentions: 0, target: 400, names: "emkay global" },
  "MANAPPURAM.NS": { pnl: 69.8, reMentions: 5, target: 315, names: "manapuram" },
  "SMSPHARMA.NS": { pnl: 69.4, reMentions: 0, target: null, names: "sms pharma" },
  "MCLEODRUSS.NS": { pnl: 69.3, reMentions: 0, target: 35, names: "mcleod russell" },
  "JINDALSTEL.NS": { pnl: 69.1, reMentions: 1, target: null, names: "jspl" },
  "IMFA.NS": { pnl: 65.8, reMentions: 1, target: 500, names: "imfa" },
  "HAL.NS": { pnl: 64.9, reMentions: 0, target: null, names: "hal" },
  "RTNPOWER.NS": { pnl: 63.3, reMentions: 0, target: null, names: "ratan power" },
  "PARAGMILK.NS": { pnl: 63.2, reMentions: 0, target: 175, names: "parag milk" },
  "BFUTILITIE.NS": { pnl: 61.5, reMentions: 6, target: 500, names: "bf utility" },
  "BANKINDIA.NS": { pnl: 58.2, reMentions: 3, target: 90, names: "bank of india" },
  "NMDC.NS": { pnl: 55.1, reMentions: 1, target: 50, names: "nmdc" },
  "GODREJPROP.NS": { pnl: 54.6, reMentions: 1, target: 2000, names: "godrej property" },
  "EXIDEIND.NS": { pnl: 52.9, reMentions: 0, target: null, names: "exide" },
  "MUTHOOTFIN.NS": { pnl: 52.8, reMentions: 1, target: null, names: "muthooth" },
  "ITC.NS": { pnl: 51.0, reMentions: 0, target: null, names: "itc" },
  "PTCIL.NS": { pnl: 49.3, reMentions: 2, target: 50, names: "ptc ind" },
  "MANINFRA.NS": { pnl: 42.1, reMentions: 1, target: null, names: "man infra" },
  "SUNTV.NS": { pnl: 42.0, reMentions: 0, target: 1100, names: "sun tv" },
  "BBTC.NS": { pnl: 41.7, reMentions: 0, target: null, names: "bbtc" },
  "COALINDIA.NS": { pnl: 39.6, reMentions: 0, target: 50, names: "coal india" },
  "JINDALSAW.NS": { pnl: 38.4, reMentions: 1, target: 50, names: "jindal saw" },
  "ONGC.NS": { pnl: 37.6, reMentions: 0, target: 155, names: "ongc" },
  "LUXIND.NS": { pnl: 37.4, reMentions: 0, target: 4000, names: "lux" },
  "BHARATFORG.NS": { pnl: 35.5, reMentions: 0, target: 5000, names: "bharat forge" },
  "INDUSTOWER.NS": { pnl: 32.8, reMentions: 4, target: 175, names: "industower" },
  "PCBL.NS": { pnl: 28.5, reMentions: 1, target: 175, names: "pcbl" },
  "GESHIP.NS": { pnl: 28.0, reMentions: 0, target: 50, names: "ge shipping" },
  "GHCLTEXTIL.NS": { pnl: 24.5, reMentions: 0, target: null, names: "ghcl textile" },
  "HFCL.NS": { pnl: 23.0, reMentions: 7, target: 200, names: "hfcl" },
  "DCAL.NS": { pnl: 21.6, reMentions: 7, target: 270, names: "dishman" },
  "CAPACITE.NS": { pnl: 20.2, reMentions: 0, target: 75, names: "capacity infra" },
  "SOMICONVEY.NS": { pnl: 20.1, reMentions: 0, target: 28, names: "somi conveyor" },
  "LLOYDSENGG.NS": { pnl: 19.8, reMentions: 0, target: 36, names: "lloyed enterprise" },
  "KAYA.NS": { pnl: 19.4, reMentions: 0, target: null, names: "kaya" },
  "BOMDYEING.NS": { pnl: 19.3, reMentions: 4, target: null, names: "bombay dying" },
  "SAIL.NS": { pnl: 18.3, reMentions: 2, target: 16, names: "sail" },
  "RELINFRA.NS": { pnl: 17.4, reMentions: 5, target: 242, names: "rel infra" },
  "FIEMIND.NS": { pnl: 14.0, reMentions: 1, target: 90, names: "shigen" },
  "NIDAN.NS": { pnl: 11.4, reMentions: 1, target: 38, names: "nidan" },
  "BALAJITELE.NS": { pnl: 10.6, reMentions: 5, target: 175, names: "balaji tele" },
  "HDFCBANK.NS": { pnl: 9.8, reMentions: 2, target: 1550, names: "hdfc bank" },
  "GRINFRA.NS": { pnl: 9.6, reMentions: 0, target: null, names: "gr infra" },
  "TARSONS.NS": { pnl: 9.5, reMentions: 1, target: null, names: "tarsons" },
  "NAVKARCORP.NS": { pnl: 9.4, reMentions: 4, target: 260, names: "navkar corp" },
  "NTPC.NS": { pnl: 7.8, reMentions: 0, target: null, names: "ntpc" },
  "KAYNES.NS": { pnl: 7.5, reMentions: 1, target: null, names: "kaynes" },
  "IBREALEST.NS": { pnl: 6.7, reMentions: 2, target: 175, names: "ibull real" },
  "AGSTRA.NS": { pnl: 4.3, reMentions: 0, target: 550, names: "ags transact" },
  "GHCL.NS": { pnl: 3.2, reMentions: 0, target: 2022, names: "ghcl" },
  "DCW.NS": { pnl: 3.0, reMentions: 0, target: 52, names: "dcw" },
  "SAHYADRI.NS": { pnl: 3.0, reMentions: 0, target: 200, names: "sahyadri" },
  "IDBI.NS": { pnl: 2.1, reMentions: 2, target: 5000, names: "idbi" },
  "LICHSGFIN.NS": { pnl: 0.9, reMentions: 0, target: null, names: "lic housing" },
  "CSBBANK.NS": { pnl: 0.9, reMentions: 2, target: 75, names: "csb bank" },
  "RAIN.NS": { pnl: 0.0, reMentions: 2, target: null, names: "rain ind" },
  "EKC.NS": { pnl: -0.1, reMentions: 1, target: 250, names: "ekc" },
  "BANKBARODA.NS": { pnl: -0.4, reMentions: 1, target: 175, names: "bob" },
  "SHANTIGOLD.NS": { pnl: -0.9, reMentions: 3, target: null, names: "shanti gold" },
  "HERANBA.NS": { pnl: -1.3, reMentions: 0, target: 330, names: "hernaba" },
  "ICICIBANK.NS": { pnl: -2.2, reMentions: 1, target: 175, names: "icici" },
  "EDELWEISS.NS": { pnl: -2.5, reMentions: 1, target: null, names: "edelweiss" },
  "GRASIM.NS": { pnl: -3.6, reMentions: 1, target: 175, names: "grasim" },
  "TATASTEEL.NS": { pnl: -6.2, reMentions: 0, target: null, names: "tisco" },
  "AMBUJACEM.NS": { pnl: -6.3, reMentions: 0, target: null, names: "ambuja" },
  "LXCHEM.NS": { pnl: -7.6, reMentions: 0, target: 550, names: "laxmi organics" },
  "VAKRANGEE.NS": { pnl: -8.9, reMentions: 4, target: 45, names: "vakrangi" },
  "PGEL.NS": { pnl: -10.6, reMentions: 1, target: null, names: "pg" },
  "ZEEL.NS": { pnl: -12.5, reMentions: 5, target: 175, names: "zee" },
  "PNB.NS": { pnl: -12.7, reMentions: 2, target: 175, names: "pnb" },
  "ELECTCAST.NS": { pnl: -13.3, reMentions: 1, target: 270, names: "electrosteel" },
  "VINDHYATEL.NS": { pnl: -15.3, reMentions: 0, target: 5500, names: "vindhya tele" },
  "DISHTV.NS": { pnl: -15.5, reMentions: 2, target: null, names: "dish tv" },
  "CAMLINFINE.NS": { pnl: -15.6, reMentions: 0, target: null, names: "camlin fine" },
  "MAHLIFE.NS": { pnl: -16.8, reMentions: 0, target: null, names: "mahindralife" },
  "DBREALTY.NS": { pnl: -19.3, reMentions: 0, target: null, names: "db reality" },
  "STEELXIND.NS": { pnl: -46.8, reMentions: 2, target: 25, names: "steel exchange" },
  "BGRENERGY.NS": { pnl: -61.9, reMentions: 0, target: null, names: "bgr energy" },
};
